plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
}

version = '1.0.8'
group = 'com.example'

base {
    archivesName = 'blacksmith-epic-patch'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', 'blacksmith_epic_patch'
            
            mods {
                blacksmith_epic_patch {
                    source sourceSets.main
                }
                reignofnether {
                    source sourceSets.main
                }
                magistuarmory {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven {
        name = 'Minecraft Forge'
        url = 'https://maven.minecraftforge.net/'
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.16'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
